In [ ]:
import pandas as pd


csv_path = "subject-1.csv"

trial_data = pd.read_csv(csv_path)

In [ ]:
trial_data_gezeigt = trial_data[trial_data["skip_trial"] == 0]
display(trial_data_gezeigt)

,AN,Code,RN,acc,accuracy,an_found,an_height,an_line,an_text,an_width,...,title,total_correct,total_response_time,total_responses,trial_counter,width,word,word_height,word_spacing,word_width
0,<AN>Frauen</AN>,C6,<RN>Expert*innen</RN>,undefined,undefined,True,53,4,<AN>Frauen</AN>,132,...,Experiment,0,0,0,1,1920,bewertet.,53,25,197
1,<AN>Frauen</AN>,C4,<RN>Lehrerinnen</RN>,undefined,undefined,True,53,4,<AN>Frauen</AN>,132,...,Experiment,0,0,0,2,1920,Diskussionen.,53,25,289
8,<AN>Männer</AN>,C3,<RN>Ingenieurinnen</RN>,undefined,undefined,True,53,4,<AN>Männer</AN>,135,...,Experiment,0,0,0,3,1920,diskutiert.,53,25,243
11,<AN>Männern</AN>,C5,<RN>Einwohner*innen</RN>,undefined,undefined,True,53,4,<AN>Männern</AN>,158,...,Experiment,0,0,0,4,1920,Debatten.,53,25,197
24,<AN>Frauen</AN>,C6,<RN>Einwohner*innen</RN>,undefined,undefined,True,53,4,<AN>Frauen</AN>,132,...,Experiment,0,0,0,5,1920,Reaktionen.,53,25,242
35,<AN>Frauen</AN>,C2,<RN>Experten</RN>,undefined,undefined,True,53,4,<AN>Frauen</AN>,132,...,Experiment,0,0,0,6,1920,geprüft.,53,25,175
37,<AN>Frauen</AN>,C6,<RN>Pfleger*innen</RN>,undefined,undefined,True,53,4,<AN>Frauen</AN>,132,...,Experiment,0,0,0,7,1920,diskutiert.,53,25,243
39,<AN>Frauen</AN>,C2,<RN>Unternehmer</RN>,undefined,undefined,True,53,4,<AN>Frauen</AN>,132,...,Experiment,0,0,0,8,1920,umstritten.,53,25,243
40,<AN>Männer</AN>,C5,<RN>Student*innen</RN>,undefined,undefined,True,53,4,<AN>Männer</AN>,135,...,Experiment,0,0,0,9,1920,Debatten.,53,25,197
49,<AN>Männer</AN>,C3,<RN>Aktivistinnen</RN>,undefined,undefined,True,53,4,<AN>Männer</AN>,135,...,Experiment,0,0,0,10,1920,geprüft.,53,25,175
50,<AN>Männer</AN>,C1,<RN>Professoren</RN>,undefined,undefined,True,53,4,<AN>Männer</AN>,135,...,Experiment,0,0,0,11,1920,diskutiert.,53,25,243
63,<AN>Frauen</AN>,C4,<RN>Polizistinnen</RN>,undefined,undefined,True,53,4,<AN>Frauen</AN>,132,...,Experiment,0,0,0,12,1920,verhandelt.,53,25,244
65,<AN>Männer</AN>,C5,<RN>Expert*innen</RN>,undefined,undefined,True,53,4,<AN>Männer</AN>,135,...,Experiment,0,0,0,13,1920,bewertet.,53,25,197
67,<AN>Männer</AN>,C1,<RN>Ingenieure</RN>,undefined,undefined,True,53,4,<AN>Männer</AN>,135,...,Experiment,0,0,0,14,1920,gestritten.,53,25,244
75,<AN>Männer</AN>,C3,<RN>Arbeitnehmerinnen</RN>,undefined,undefined,True,53,4,<AN>Männer</AN>,135,...,Experiment,0,0,0,15,1920,offen.,53,25,129
89,<AN>Frauen</AN>,C4,<RN>Arbeitnehmerinnen</RN>,undefined,undefined,True,53,4,<AN>Frauen</AN>,132,...,Experiment,0,0,0,16,1920,Diskussionen.,53,25,289
90,<AN>Männer</AN>,C1,<RN>Dozenten</RN>,undefined,undefined,True,53,4,<AN>Männer</AN>,135,...,Experiment,0,0,0,17,1920,an.,53,25,59
96,<AN>Frauen</AN>,C2,<RN>Krankenpfleger</RN>,undefined,undefined,True,53,4,<AN>Frauen</AN>,132,...,Experiment,0,0,0,18,1920,diskutiert.,53,25,243

In [ ]:
# Nur gezeigte Trials
trial_data_gezeigt = trial_data[trial_data["skip_trial"] == 0]

# Gewünschte Spalten
spalten = [
    "Code","AN", "RN",
    "an_found", "an_height", "an_line", "an_width",
    "an_x1", "an_x2",
    "current_line", "current_line_width",
    "datetime",
    "display_sentence",
    "experiment_file", "experiment_path",
    "item",
    "name",
    "rn_found", "rn_height", "rn_line", "rn_text",
    "rn_width", "rn_x1", "rn_x2", "rn_y1", "rn_y2",
    "selected_list",
    "skip_trial",
    "spill_x1", "spill_x2", "spill_y1", "spill_y2",
    "trial_counter"
]

# Tabelle erzeugen
trial_data_auswahl = trial_data_gezeigt[spalten]

display(trial_data_auswahl)

,Code,AN,RN,an_found,an_height,an_line,an_width,an_x1,an_x2,current_line,...,rn_x2,rn_y1,rn_y2,selected_list,skip_trial,spill_x1,spill_x2,spill_y1,spill_y2,trial_counter
0,C6,<AN>Frauen</AN>,<RN>Expert*innen</RN>,True,53,4,132,-223.0,-91.0,5,...,-539.0,-56.0,-3.0,5,0,-91.0,41.0,61.0,114.0,1
1,C4,<AN>Frauen</AN>,<RN>Lehrerinnen</RN>,True,53,4,132,-333.0,-201.0,5,...,414.0,-173.0,-120.0,5,0,-201.0,-69.0,61.0,114.0,2
8,C3,<AN>Männer</AN>,<RN>Ingenieurinnen</RN>,True,53,4,135,-85.0,50.0,5,...,796.0,-173.0,-120.0,5,0,50.0,185.0,61.0,114.0,3
11,C5,<AN>Männern</AN>,<RN>Einwohner*innen</RN>,True,53,4,158,-309.0,-151.0,5,...,-470.0,-56.0,-3.0,5,0,-151.0,7.0,61.0,114.0,4
24,C6,<AN>Frauen</AN>,<RN>Einwohner*innen</RN>,True,53,4,132,-179.0,-47.0,5,...,-470.0,-56.0,-3.0,5,0,-47.0,85.0,61.0,114.0,5
35,C2,<AN>Frauen</AN>,<RN>Experten</RN>,True,53,4,132,-63.0,69.0,5,...,-472.0,-56.0,-3.0,5,0,69.0,201.0,61.0,114.0,6
37,C6,<AN>Frauen</AN>,<RN>Pfleger*innen</RN>,True,53,4,132,-222.0,-90.0,6,...,-516.0,-56.0,-3.0,5,0,-90.0,42.0,61.0,114.0,7
39,C2,<AN>Frauen</AN>,<RN>Unternehmer</RN>,True,53,4,132,-197.0,-65.0,5,...,-561.0,-56.0,-3.0,5,0,-65.0,67.0,61.0,114.0,8
40,C5,<AN>Männer</AN>,<RN>Student*innen</RN>,True,53,4,135,-378.0,-243.0,5,...,419.0,-173.0,-120.0,5,0,-243.0,-108.0,61.0,114.0,9
49,C3,<AN>Männer</AN>,<RN>Aktivistinnen</RN>,True,53,4,135,-201.0,-66.0,5,...,558.0,-173.0,-120.0,5,0,-66.0,69.0,61.0,114.0,10
50,C1,<AN>Männer</AN>,<RN>Professoren</RN>,True,53,4,135,-65.0,70.0,5,...,709.0,-173.0,-120.0,5,0,70.0,205.0,61.0,114.0,11
63,C4,<AN>Frauen</AN>,<RN>Polizistinnen</RN>,True,53,4,132,-202.0,-70.0,5,...,281.0,-173.0,-120.0,5,0,-70.0,62.0,61.0,114.0,12
65,C5,<AN>Männer</AN>,<RN>Expert*innen</RN>,True,53,4,135,-309.0,-174.0,5,...,-539.0,-56.0,-3.0,5,0,-174.0,-39.0,61.0,114.0,13
67,C1,<AN>Männer</AN>,<RN>Ingenieure</RN>,True,53,4,135,-130.0,5.0,5,...,-585.0,-56.0,-3.0,5,0,5.0,140.0,61.0,114.0,14
75,C3,<AN>Männer</AN>,<RN>Arbeitnehmerinnen</RN>,True,53,4,135,-220.0,-85.0,5,...,-421.0,-56.0,-3.0,5,0,-85.0,50.0,61.0,114.0,15
89,C4,<AN>Frauen</AN>,<RN>Arbeitnehmerinnen</RN>,True,53,4,132,-105.0,27.0,6,...,-421.0,-56.0,-3.0,5,0,27.0,159.0,61.0,114.0,16
90,C1,<AN>Männer</AN>,<RN>Dozenten</RN>,True,53,4,135,-339.0,-204.0,5,...,668.0,-173.0,-120.0,5,0,-204.0,-69.0,61.0,114.0,17
96,C2,<AN>Frauen</AN>,<RN>Krankenpfleger</RN>,True,53,4,132,-131.0,1.0,5,...,687.0,-173.0,-120.0,5,0,1.0,133.0,61.0,114.0,18

In [ ]:
# Nur gezeigte Trials
trial_data_gezeigt = trial_data[trial_data["skip_trial"] == 0]

# Tabelle erzeugen
trial_data_auswahl = trial_data_gezeigt[spalten]

# Nach Code sortieren
trial_data_auswahl = trial_data_auswahl.sort_values(by="Code")

display(trial_data_auswahl)

,Code,AN,RN,an_found,an_height,an_line,an_width,an_x1,an_x2,current_line,...,rn_x2,rn_y1,rn_y2,selected_list,skip_trial,spill_x1,spill_x2,spill_y1,spill_y2,trial_counter
67,C1,<AN>Männer</AN>,<RN>Ingenieure</RN>,True,53,4,135,-130.0,5.0,5,...,-585.0,-56.0,-3.0,5,0,5.0,140.0,61.0,114.0,14
90,C1,<AN>Männer</AN>,<RN>Dozenten</RN>,True,53,4,135,-339.0,-204.0,5,...,668.0,-173.0,-120.0,5,0,-204.0,-69.0,61.0,114.0,17
50,C1,<AN>Männer</AN>,<RN>Professoren</RN>,True,53,4,135,-65.0,70.0,5,...,709.0,-173.0,-120.0,5,0,70.0,205.0,61.0,114.0,11
96,C2,<AN>Frauen</AN>,<RN>Krankenpfleger</RN>,True,53,4,132,-131.0,1.0,5,...,687.0,-173.0,-120.0,5,0,1.0,133.0,61.0,114.0,18
35,C2,<AN>Frauen</AN>,<RN>Experten</RN>,True,53,4,132,-63.0,69.0,5,...,-472.0,-56.0,-3.0,5,0,69.0,201.0,61.0,114.0,6
39,C2,<AN>Frauen</AN>,<RN>Unternehmer</RN>,True,53,4,132,-197.0,-65.0,5,...,-561.0,-56.0,-3.0,5,0,-65.0,67.0,61.0,114.0,8
8,C3,<AN>Männer</AN>,<RN>Ingenieurinnen</RN>,True,53,4,135,-85.0,50.0,5,...,796.0,-173.0,-120.0,5,0,50.0,185.0,61.0,114.0,3
75,C3,<AN>Männer</AN>,<RN>Arbeitnehmerinnen</RN>,True,53,4,135,-220.0,-85.0,5,...,-421.0,-56.0,-3.0,5,0,-85.0,50.0,61.0,114.0,15
49,C3,<AN>Männer</AN>,<RN>Aktivistinnen</RN>,True,53,4,135,-201.0,-66.0,5,...,558.0,-173.0,-120.0,5,0,-66.0,69.0,61.0,114.0,10
1,C4,<AN>Frauen</AN>,<RN>Lehrerinnen</RN>,True,53,4,132,-333.0,-201.0,5,...,414.0,-173.0,-120.0,5,0,-201.0,-69.0,61.0,114.0,2
89,C4,<AN>Frauen</AN>,<RN>Arbeitnehmerinnen</RN>,True,53,4,132,-105.0,27.0,6,...,-421.0,-56.0,-3.0,5,0,27.0,159.0,61.0,114.0,16
63,C4,<AN>Frauen</AN>,<RN>Polizistinnen</RN>,True,53,4,132,-202.0,-70.0,5,...,281.0,-173.0,-120.0,5,0,-70.0,62.0,61.0,114.0,12
40,C5,<AN>Männer</AN>,<RN>Student*innen</RN>,True,53,4,135,-378.0,-243.0,5,...,419.0,-173.0,-120.0,5,0,-243.0,-108.0,61.0,114.0,9
11,C5,<AN>Männern</AN>,<RN>Einwohner*innen</RN>,True,53,4,158,-309.0,-151.0,5,...,-470.0,-56.0,-3.0,5,0,-151.0,7.0,61.0,114.0,4
65,C5,<AN>Männer</AN>,<RN>Expert*innen</RN>,True,53,4,135,-309.0,-174.0,5,...,-539.0,-56.0,-3.0,5,0,-174.0,-39.0,61.0,114.0,13
37,C6,<AN>Frauen</AN>,<RN>Pfleger*innen</RN>,True,53,4,132,-222.0,-90.0,6,...,-516.0,-56.0,-3.0,5,0,-90.0,42.0,61.0,114.0,7
24,C6,<AN>Frauen</AN>,<RN>Einwohner*innen</RN>,True,53,4,132,-179.0,-47.0,5,...,-470.0,-56.0,-3.0,5,0,-47.0,85.0,61.0,114.0,5
0,C6,<AN>Frauen</AN>,<RN>Expert*innen</RN>,True,53,4,132,-223.0,-91.0,5,...,-539.0,-56.0,-3.0,5,0,-91.0,41.0,61.0,114.0,1