In [ ]:
import pandas as pd


csv_path = "subject-4.csv"

trial_data = pd.read_csv(csv_path)

In [10]:
trial_data_gezeigt = trial_data[trial_data["skip_trial"] == 0]
display(trial_data_gezeigt)

,AN,Code,RN,acc,accuracy,an_found,an_height,an_line,an_text,an_width,...,title,total_correct,total_response_time,total_responses,trial_counter,width,word,word_height,word_spacing,word_width
5,<AN>Frauen</AN>,C6,<RN>Unternehmer*innen</RN>,undefined,undefined,True,53.0,4.0,<AN>Frauen</AN>,132.0,...,Experiment,0,0,0,1,1920,umstritten.,53.0,25.0,243.0
9,<AN>Frauen</AN>,C6,<RN>Expert*innen</RN>,undefined,undefined,True,53.0,4.0,<AN>Frauen</AN>,132.0,...,Experiment,0,0,0,2,1920,geprüft.,53.0,25.0,175.0
32,<AN>Männer</AN>,C5,<RN>Professor*innen</RN>,undefined,undefined,True,53.0,4.0,<AN>Männer</AN>,135.0,...,Experiment,0,0,0,3,1920,diskutiert.,53.0,25.0,243.0
34,<AN>Männer</AN>,C1,<RN>Arbeitnehmer</RN>,undefined,undefined,True,53.0,4.0,<AN>Männer</AN>,135.0,...,Experiment,0,0,0,4,1920,offen.,53.0,25.0,129.0
41,<AN>Männer</AN>,C1,<RN>Aktivisten</RN>,undefined,undefined,True,53.0,4.0,<AN>Männer</AN>,135.0,...,Experiment,0,0,0,5,1920,geprüft.,53.0,25.0,175.0
42,<AN>Frauen</AN>,C4,<RN>Expertinnen</RN>,undefined,undefined,True,53.0,4.0,<AN>Frauen</AN>,132.0,...,Experiment,0,0,0,6,1920,bewertet.,53.0,25.0,197.0
43,<AN>Männer</AN>,C3,<RN>Studentinnen</RN>,undefined,undefined,True,53.0,4.0,<AN>Männer</AN>,135.0,...,Experiment,0,0,0,7,1920,Debatten.,53.0,25.0,197.0
57,<AN>Männer</AN>,C5,<RN>Dozent*innen</RN>,undefined,undefined,True,53.0,4.0,<AN>Männer</AN>,135.0,...,Experiment,0,0,0,8,1920,an.,53.0,25.0,59.0
58,<AN>Frauen</AN>,C6,<RN>Krankenpfleger*innen</RN>,undefined,undefined,True,53.0,4.0,<AN>Frauen</AN>,132.0,...,Experiment,0,0,0,9,1920,diskutiert.,53.0,25.0,243.0
59,<AN>Frauen</AN>,C4,<RN>Einwohnerinnen</RN>,undefined,undefined,True,53.0,4.0,<AN>Frauen</AN>,132.0,...,Experiment,0,0,0,10,1920,Reaktionen.,53.0,25.0,242.0
67,<AN>Männer</AN>,C3,<RN>Expertinnen</RN>,undefined,undefined,True,53.0,4.0,<AN>Männer</AN>,135.0,...,Experiment,0,0,0,11,1920,bewertet.,53.0,25.0,197.0
71,<AN>Frauen</AN>,C2,<RN>Polizisten</RN>,undefined,undefined,True,53.0,4.0,<AN>Frauen</AN>,132.0,...,Experiment,0,0,0,12,1920,verhandelt.,53.0,25.0,244.0
73,<AN>Frauen</AN>,C4,<RN>Pflegerinnen</RN>,undefined,undefined,True,53.0,4.0,<AN>Frauen</AN>,132.0,...,Experiment,0,0,0,13,1920,diskutiert.,53.0,25.0,243.0
79,<AN>Frauen</AN>,C2,<RN>Lehrer</RN>,undefined,undefined,True,53.0,4.0,<AN>Frauen</AN>,132.0,...,Experiment,0,0,0,14,1920,Diskussionen.,53.0,25.0,289.0
80,<AN>Männern</AN>,C3,<RN>Einwohnerinnen</RN>,undefined,undefined,True,53.0,4.0,<AN>Männern</AN>,158.0,...,Experiment,0,0,0,15,1920,Debatten.,53.0,25.0,197.0
88,<AN>Frauen</AN>,C2,<RN>Arbeitnehmer</RN>,undefined,undefined,True,53.0,4.0,<AN>Frauen</AN>,132.0,...,Experiment,0,0,0,16,1920,Diskussionen.,53.0,25.0,289.0
94,<AN>Männer</AN>,C5,<RN>Ingenieur*innen</RN>,undefined,undefined,True,53.0,4.0,<AN>Männer</AN>,135.0,...,Experiment,0,0,0,17,1920,gestritten.,53.0,25.0,244.0
97,<AN>Männer</AN>,C1,<RN>Ingenieure</RN>,undefined,undefined,True,53.0,4.0,<AN>Männer</AN>,135.0,...,Experiment,0,0,0,18,1920,diskutiert.,53.0,25.0,243.0

In [11]:
# Nur gezeigte Trials
trial_data_gezeigt = trial_data[trial_data["skip_trial"] == 0]

# Gewünschte Spalten
spalten = [
    "Code","AN", "RN",
    "an_found", "an_height", "an_line", "an_width",
    "an_x1", "an_x2",
    "current_line", "current_line_width",
    "datetime",
    "display_sentence",
    "experiment_file", "experiment_path",
    "item",
    "name",
    "rn_found", "rn_height", "rn_line", "rn_text",
    "rn_width", "rn_x1", "rn_x2", "rn_y1", "rn_y2",
    "selected_list",
    "skip_trial",
    "spill_x1", "spill_x2", "spill_y1", "spill_y2",
    "trial_counter"
]

# Tabelle erzeugen
trial_data_auswahl = trial_data_gezeigt[spalten]

display(trial_data_auswahl)

,Code,AN,RN,an_found,an_height,an_line,an_width,an_x1,an_x2,current_line,...,rn_x2,rn_y1,rn_y2,selected_list,skip_trial,spill_x1,spill_x2,spill_y1,spill_y2,trial_counter
5,C6,<AN>Frauen</AN>,<RN>Unternehmer*innen</RN>,True,53.0,4.0,132.0,-84.0,48.0,5.0,...,-423.0,-56.0,-3.0,3,0,48.0,180.0,61.0,114.0,1
9,C6,<AN>Frauen</AN>,<RN>Expert*innen</RN>,True,53.0,4.0,132.0,-63.0,69.0,5.0,...,-380.0,-56.0,-3.0,3,0,69.0,201.0,61.0,114.0,2
32,C5,<AN>Männer</AN>,<RN>Professor*innen</RN>,True,53.0,4.0,135.0,-65.0,70.0,5.0,...,801.0,-173.0,-120.0,3,0,70.0,205.0,61.0,114.0,3
34,C1,<AN>Männer</AN>,<RN>Arbeitnehmer</RN>,True,53.0,4.0,135.0,-305.0,-170.0,5.0,...,-536.0,-56.0,-3.0,3,0,-170.0,-35.0,61.0,114.0,4
41,C1,<AN>Männer</AN>,<RN>Aktivisten</RN>,True,53.0,4.0,135.0,-201.0,-66.0,5.0,...,489.0,-173.0,-120.0,3,0,-66.0,69.0,61.0,114.0,5
42,C4,<AN>Frauen</AN>,<RN>Expertinnen</RN>,True,53.0,4.0,132.0,-223.0,-91.0,5.0,...,-562.0,-56.0,-3.0,3,0,-91.0,41.0,61.0,114.0,6
43,C3,<AN>Männer</AN>,<RN>Studentinnen</RN>,True,53.0,4.0,135.0,-219.0,-84.0,5.0,...,602.0,-173.0,-120.0,3,0,-84.0,51.0,61.0,114.0,7
57,C5,<AN>Männer</AN>,<RN>Dozent*innen</RN>,True,53.0,4.0,135.0,-339.0,-204.0,5.0,...,760.0,-173.0,-120.0,3,0,-204.0,-69.0,61.0,114.0,8
58,C6,<AN>Frauen</AN>,<RN>Krankenpfleger*innen</RN>,True,53.0,4.0,132.0,-17.0,115.0,5.0,...,-355.0,-56.0,-3.0,3,0,115.0,247.0,61.0,114.0,9
59,C4,<AN>Frauen</AN>,<RN>Einwohnerinnen</RN>,True,53.0,4.0,132.0,-89.0,43.0,5.0,...,-493.0,-56.0,-3.0,3,0,43.0,175.0,61.0,114.0,10
67,C3,<AN>Männer</AN>,<RN>Expertinnen</RN>,True,53.0,4.0,135.0,-309.0,-174.0,5.0,...,-562.0,-56.0,-3.0,3,0,-174.0,-39.0,61.0,114.0,11
71,C2,<AN>Frauen</AN>,<RN>Polizisten</RN>,True,53.0,4.0,132.0,-202.0,-70.0,5.0,...,212.0,-173.0,-120.0,3,0,-70.0,62.0,61.0,114.0,12
73,C4,<AN>Frauen</AN>,<RN>Pflegerinnen</RN>,True,53.0,4.0,132.0,-222.0,-90.0,6.0,...,-539.0,-56.0,-3.0,3,0,-90.0,42.0,61.0,114.0,13
79,C2,<AN>Frauen</AN>,<RN>Lehrer</RN>,True,53.0,4.0,132.0,-333.0,-201.0,5.0,...,299.0,-173.0,-120.0,3,0,-201.0,-69.0,61.0,114.0,14
80,C3,<AN>Männern</AN>,<RN>Einwohnerinnen</RN>,True,53.0,4.0,158.0,-309.0,-151.0,5.0,...,-493.0,-56.0,-3.0,3,0,-151.0,7.0,61.0,114.0,15
88,C2,<AN>Frauen</AN>,<RN>Arbeitnehmer</RN>,True,53.0,4.0,132.0,-329.0,-197.0,5.0,...,788.0,-173.0,-120.0,3,0,-197.0,-65.0,61.0,114.0,16
94,C5,<AN>Männer</AN>,<RN>Ingenieur*innen</RN>,True,53.0,4.0,135.0,-130.0,5.0,5.0,...,-471.0,-56.0,-3.0,3,0,5.0,140.0,61.0,114.0,17
97,C1,<AN>Männer</AN>,<RN>Ingenieure</RN>,True,53.0,4.0,135.0,-335.0,-200.0,5.0,...,705.0,-173.0,-120.0,3,0,-200.0,-65.0,61.0,114.0,18

In [12]:
# Nur gezeigte Trials
trial_data_gezeigt = trial_data[trial_data["skip_trial"] == 0]

# Tabelle erzeugen
trial_data_auswahl = trial_data_gezeigt[spalten]

# Nach Code sortieren
trial_data_auswahl = trial_data_auswahl.sort_values(by="Code")

display(trial_data_auswahl)

,Code,AN,RN,an_found,an_height,an_line,an_width,an_x1,an_x2,current_line,...,rn_x2,rn_y1,rn_y2,selected_list,skip_trial,spill_x1,spill_x2,spill_y1,spill_y2,trial_counter
97,C1,<AN>Männer</AN>,<RN>Ingenieure</RN>,True,53.0,4.0,135.0,-335.0,-200.0,5.0,...,705.0,-173.0,-120.0,3,0,-200.0,-65.0,61.0,114.0,18
34,C1,<AN>Männer</AN>,<RN>Arbeitnehmer</RN>,True,53.0,4.0,135.0,-305.0,-170.0,5.0,...,-536.0,-56.0,-3.0,3,0,-170.0,-35.0,61.0,114.0,4
41,C1,<AN>Männer</AN>,<RN>Aktivisten</RN>,True,53.0,4.0,135.0,-201.0,-66.0,5.0,...,489.0,-173.0,-120.0,3,0,-66.0,69.0,61.0,114.0,5
88,C2,<AN>Frauen</AN>,<RN>Arbeitnehmer</RN>,True,53.0,4.0,132.0,-329.0,-197.0,5.0,...,788.0,-173.0,-120.0,3,0,-197.0,-65.0,61.0,114.0,16
71,C2,<AN>Frauen</AN>,<RN>Polizisten</RN>,True,53.0,4.0,132.0,-202.0,-70.0,5.0,...,212.0,-173.0,-120.0,3,0,-70.0,62.0,61.0,114.0,12
79,C2,<AN>Frauen</AN>,<RN>Lehrer</RN>,True,53.0,4.0,132.0,-333.0,-201.0,5.0,...,299.0,-173.0,-120.0,3,0,-201.0,-69.0,61.0,114.0,14
43,C3,<AN>Männer</AN>,<RN>Studentinnen</RN>,True,53.0,4.0,135.0,-219.0,-84.0,5.0,...,602.0,-173.0,-120.0,3,0,-84.0,51.0,61.0,114.0,7
67,C3,<AN>Männer</AN>,<RN>Expertinnen</RN>,True,53.0,4.0,135.0,-309.0,-174.0,5.0,...,-562.0,-56.0,-3.0,3,0,-174.0,-39.0,61.0,114.0,11
80,C3,<AN>Männern</AN>,<RN>Einwohnerinnen</RN>,True,53.0,4.0,158.0,-309.0,-151.0,5.0,...,-493.0,-56.0,-3.0,3,0,-151.0,7.0,61.0,114.0,15
42,C4,<AN>Frauen</AN>,<RN>Expertinnen</RN>,True,53.0,4.0,132.0,-223.0,-91.0,5.0,...,-562.0,-56.0,-3.0,3,0,-91.0,41.0,61.0,114.0,6
59,C4,<AN>Frauen</AN>,<RN>Einwohnerinnen</RN>,True,53.0,4.0,132.0,-89.0,43.0,5.0,...,-493.0,-56.0,-3.0,3,0,43.0,175.0,61.0,114.0,10
73,C4,<AN>Frauen</AN>,<RN>Pflegerinnen</RN>,True,53.0,4.0,132.0,-222.0,-90.0,6.0,...,-539.0,-56.0,-3.0,3,0,-90.0,42.0,61.0,114.0,13
32,C5,<AN>Männer</AN>,<RN>Professor*innen</RN>,True,53.0,4.0,135.0,-65.0,70.0,5.0,...,801.0,-173.0,-120.0,3,0,70.0,205.0,61.0,114.0,3
57,C5,<AN>Männer</AN>,<RN>Dozent*innen</RN>,True,53.0,4.0,135.0,-339.0,-204.0,5.0,...,760.0,-173.0,-120.0,3,0,-204.0,-69.0,61.0,114.0,8
94,C5,<AN>Männer</AN>,<RN>Ingenieur*innen</RN>,True,53.0,4.0,135.0,-130.0,5.0,5.0,...,-471.0,-56.0,-3.0,3,0,5.0,140.0,61.0,114.0,17
5,C6,<AN>Frauen</AN>,<RN>Unternehmer*innen</RN>,True,53.0,4.0,132.0,-84.0,48.0,5.0,...,-423.0,-56.0,-3.0,3,0,48.0,180.0,61.0,114.0,1
9,C6,<AN>Frauen</AN>,<RN>Expert*innen</RN>,True,53.0,4.0,132.0,-63.0,69.0,5.0,...,-380.0,-56.0,-3.0,3,0,69.0,201.0,61.0,114.0,2
58,C6,<AN>Frauen</AN>,<RN>Krankenpfleger*innen</RN>,True,53.0,4.0,132.0,-17.0,115.0,5.0,...,-355.0,-56.0,-3.0,3,0,115.0,247.0,61.0,114.0,9