In [1]:
import pandas as pd


csv_path = "../data/raw/subject-1.csv"

trial_data = pd.read_csv(csv_path)

In [2]:
trial_data_gezeigt = trial_data[trial_data["skip_trial"] == 0]
display(trial_data_gezeigt)

,AN,Code,RN,acc,accuracy,an_found,an_height,an_line,an_text,an_width,...,title,total_correct,total_response_time,total_responses,trial_counter,width,word,word_height,word_spacing,word_width
1,<AN>Frauen</AN>,C4,<RN>Krankenschwestern</RN>,undefined,undefined,True,53.0,4.0,<AN>Frauen</AN>,132.0,...,Experiment,0,0,0,1,1920,diskutiert.,53.0,25.0,243.0
6,<AN>Frauen</AN>,C2,<RN>Pfleger</RN>,undefined,undefined,True,53.0,4.0,<AN>Frauen</AN>,132.0,...,Experiment,0,0,0,2,1920,diskutiert.,53.0,25.0,243.0
11,<AN>Frauen</AN>,C2,<RN>Experten</RN>,undefined,undefined,True,53.0,4.0,<AN>Frauen</AN>,132.0,...,Experiment,0,0,0,3,1920,bewertet.,53.0,25.0,197.0
14,<AN>Frauen</AN>,C2,<RN>Einwohner</RN>,undefined,undefined,True,53.0,4.0,<AN>Frauen</AN>,132.0,...,Experiment,0,0,0,4,1920,Reaktionen.,53.0,25.0,242.0
21,<AN>Männer</AN>,C5,<RN>Arbeitnehmer*innen</RN>,undefined,undefined,True,53.0,4.0,<AN>Männer</AN>,135.0,...,Experiment,0,0,0,5,1920,offen.,53.0,25.0,129.0
24,<AN>Frauen</AN>,C6,<RN>Polizist*innen</RN>,undefined,undefined,True,53.0,4.0,<AN>Frauen</AN>,132.0,...,Experiment,0,0,0,6,1920,verhandelt.,53.0,25.0,244.0
33,<AN>Frauen</AN>,C4,<RN>Unternehmerinnen</RN>,undefined,undefined,True,53.0,4.0,<AN>Frauen</AN>,132.0,...,Experiment,0,0,0,7,1920,umstritten.,53.0,25.0,243.0
43,<AN>Männer</AN>,C5,<RN>Ingenieur*innen</RN>,undefined,undefined,True,53.0,4.0,<AN>Männer</AN>,135.0,...,Experiment,0,0,0,8,1920,diskutiert.,53.0,25.0,243.0
44,<AN>Männern</AN>,C1,<RN>Einwohner</RN>,undefined,undefined,True,53.0,4.0,<AN>Männern</AN>,158.0,...,Experiment,0,0,0,9,1920,Debatten.,53.0,25.0,197.0
51,<AN>Männer</AN>,C1,<RN>Experten</RN>,undefined,undefined,True,53.0,4.0,<AN>Männer</AN>,135.0,...,Experiment,0,0,0,10,1920,bewertet.,53.0,25.0,197.0
64,<AN>Männer</AN>,C5,<RN>Aktivist*innen</RN>,undefined,undefined,True,53.0,4.0,<AN>Männer</AN>,135.0,...,Experiment,0,0,0,11,1920,geprüft.,53.0,25.0,175.0
65,<AN>Männer</AN>,C3,<RN>Dozentinnen</RN>,undefined,undefined,True,53.0,4.0,<AN>Männer</AN>,135.0,...,Experiment,0,0,0,12,1920,an.,53.0,25.0,59.0
68,<AN>Männer</AN>,C3,<RN>Professorinnen</RN>,undefined,undefined,True,53.0,4.0,<AN>Männer</AN>,135.0,...,Experiment,0,0,0,13,1920,diskutiert.,53.0,25.0,243.0
77,<AN>Frauen</AN>,C6,<RN>Lehrer*innen</RN>,undefined,undefined,True,53.0,4.0,<AN>Frauen</AN>,132.0,...,Experiment,0,0,0,14,1920,Diskussionen.,53.0,25.0,289.0
95,<AN>Männer</AN>,C1,<RN>Studenten</RN>,undefined,undefined,True,53.0,4.0,<AN>Männer</AN>,135.0,...,Experiment,0,0,0,15,1920,Debatten.,53.0,25.0,197.0
97,<AN>Frauen</AN>,C6,<RN>Arbeitnehmer*innen</RN>,undefined,undefined,True,53.0,4.0,<AN>Frauen</AN>,132.0,...,Experiment,0,0,0,16,1920,Diskussionen.,53.0,25.0,289.0
98,<AN>Frauen</AN>,C4,<RN>Expertinnen</RN>,undefined,undefined,True,53.0,4.0,<AN>Frauen</AN>,132.0,...,Experiment,0,0,0,17,1920,geprüft.,53.0,25.0,175.0
100,<AN>Männer</AN>,C3,<RN>Ingenieurinnen</RN>,undefined,undefined,True,53.0,4.0,<AN>Männer</AN>,135.0,...,Experiment,0,0,0,18,1920,gestritten.,53.0,25.0,244.0

In [3]:
# Nur gezeigte Trials
trial_data_gezeigt = trial_data[trial_data["skip_trial"] == 0]

# Gewünschte Spalten
spalten = [
    "Code","AN", "RN",
    "an_found", "an_height", "an_line", "an_width",
    "an_x1", "an_x2",
    "current_line", "current_line_width",
    "datetime",
    "display_sentence",
    "experiment_file", "experiment_path",
    "item",
    "name",
    "rn_found", "rn_height", "rn_line", "rn_text",
    "rn_width", "rn_x1", "rn_x2", "rn_y1", "rn_y2",
    "selected_list",
    "skip_trial",
    "spill_x1", "spill_x2", "spill_y1", "spill_y2",
    "trial_counter"
]

# Tabelle erzeugen
trial_data_auswahl = trial_data_gezeigt[spalten]

display(trial_data_auswahl)

,Code,AN,RN,an_found,an_height,an_line,an_width,an_x1,an_x2,current_line,...,rn_x2,rn_y1,rn_y2,selected_list,skip_trial,spill_x1,spill_x2,spill_y1,spill_y2,trial_counter
1,C4,<AN>Frauen</AN>,<RN>Krankenschwestern</RN>,True,53.0,4.0,132.0,-131.0,1.0,5.0,...,756.0,-173.0,-120.0,1,0,1.0,133.0,61.0,114.0,1
6,C2,<AN>Frauen</AN>,<RN>Pfleger</RN>,True,53.0,4.0,132.0,-222.0,-90.0,6.0,...,737.0,-173.0,-120.0,1,0,-90.0,42.0,61.0,114.0,2
11,C2,<AN>Frauen</AN>,<RN>Experten</RN>,True,53.0,4.0,132.0,-223.0,-91.0,5.0,...,-631.0,-56.0,-3.0,1,0,-91.0,41.0,61.0,114.0,3
14,C2,<AN>Frauen</AN>,<RN>Einwohner</RN>,True,53.0,4.0,132.0,-179.0,-47.0,5.0,...,-608.0,-56.0,-3.0,1,0,-47.0,85.0,61.0,114.0,4
21,C5,<AN>Männer</AN>,<RN>Arbeitnehmer*innen</RN>,True,53.0,4.0,135.0,-220.0,-85.0,5.0,...,-398.0,-56.0,-3.0,1,0,-85.0,50.0,61.0,114.0,5
24,C6,<AN>Frauen</AN>,<RN>Polizist*innen</RN>,True,53.0,4.0,132.0,-202.0,-70.0,5.0,...,304.0,-173.0,-120.0,1,0,-70.0,62.0,61.0,114.0,6
33,C4,<AN>Frauen</AN>,<RN>Unternehmerinnen</RN>,True,53.0,4.0,132.0,-84.0,48.0,5.0,...,-446.0,-56.0,-3.0,1,0,48.0,180.0,61.0,114.0,7
43,C5,<AN>Männer</AN>,<RN>Ingenieur*innen</RN>,True,53.0,4.0,135.0,115.0,250.0,5.0,...,-471.0,-56.0,-3.0,1,0,250.0,385.0,61.0,114.0,8
44,C1,<AN>Männern</AN>,<RN>Einwohner</RN>,True,53.0,4.0,158.0,-309.0,-151.0,5.0,...,-608.0,-56.0,-3.0,1,0,-151.0,7.0,61.0,114.0,9
51,C1,<AN>Männer</AN>,<RN>Experten</RN>,True,53.0,4.0,135.0,-309.0,-174.0,5.0,...,-631.0,-56.0,-3.0,1,0,-174.0,-39.0,61.0,114.0,10
64,C5,<AN>Männer</AN>,<RN>Aktivist*innen</RN>,True,53.0,4.0,135.0,-201.0,-66.0,5.0,...,581.0,-173.0,-120.0,1,0,-66.0,69.0,61.0,114.0,11
65,C3,<AN>Männer</AN>,<RN>Dozentinnen</RN>,True,53.0,4.0,135.0,-339.0,-204.0,5.0,...,737.0,-173.0,-120.0,1,0,-204.0,-69.0,61.0,114.0,12
68,C3,<AN>Männer</AN>,<RN>Professorinnen</RN>,True,53.0,4.0,135.0,-65.0,70.0,5.0,...,778.0,-173.0,-120.0,1,0,70.0,205.0,61.0,114.0,13
77,C6,<AN>Frauen</AN>,<RN>Lehrer*innen</RN>,True,53.0,4.0,132.0,-333.0,-201.0,5.0,...,231.0,-173.0,-120.0,1,0,-201.0,-69.0,61.0,114.0,14
95,C1,<AN>Männer</AN>,<RN>Studenten</RN>,True,53.0,4.0,135.0,-378.0,-243.0,5.0,...,327.0,-173.0,-120.0,1,0,-243.0,-108.0,61.0,114.0,15
97,C6,<AN>Frauen</AN>,<RN>Arbeitnehmer*innen</RN>,True,53.0,4.0,132.0,-105.0,27.0,6.0,...,-398.0,-56.0,-3.0,1,0,27.0,159.0,61.0,114.0,16
98,C4,<AN>Frauen</AN>,<RN>Expertinnen</RN>,True,53.0,4.0,132.0,-63.0,69.0,5.0,...,-403.0,-56.0,-3.0,1,0,69.0,201.0,61.0,114.0,17
100,C3,<AN>Männer</AN>,<RN>Ingenieurinnen</RN>,True,53.0,4.0,135.0,-130.0,5.0,5.0,...,-494.0,-56.0,-3.0,1,0,5.0,140.0,61.0,114.0,18

In [4]:
# Nur gezeigte Trials
trial_data_gezeigt = trial_data[trial_data["skip_trial"] == 0]

# Tabelle erzeugen
trial_data_auswahl = trial_data_gezeigt[spalten]

# Nach Code sortieren
trial_data_auswahl = trial_data_auswahl.sort_values(by="Code")

display(trial_data_auswahl)

,Code,AN,RN,an_found,an_height,an_line,an_width,an_x1,an_x2,current_line,...,rn_x2,rn_y1,rn_y2,selected_list,skip_trial,spill_x1,spill_x2,spill_y1,spill_y2,trial_counter
44,C1,<AN>Männern</AN>,<RN>Einwohner</RN>,True,53.0,4.0,158.0,-309.0,-151.0,5.0,...,-608.0,-56.0,-3.0,1,0,-151.0,7.0,61.0,114.0,9
95,C1,<AN>Männer</AN>,<RN>Studenten</RN>,True,53.0,4.0,135.0,-378.0,-243.0,5.0,...,327.0,-173.0,-120.0,1,0,-243.0,-108.0,61.0,114.0,15
51,C1,<AN>Männer</AN>,<RN>Experten</RN>,True,53.0,4.0,135.0,-309.0,-174.0,5.0,...,-631.0,-56.0,-3.0,1,0,-174.0,-39.0,61.0,114.0,10
6,C2,<AN>Frauen</AN>,<RN>Pfleger</RN>,True,53.0,4.0,132.0,-222.0,-90.0,6.0,...,737.0,-173.0,-120.0,1,0,-90.0,42.0,61.0,114.0,2
11,C2,<AN>Frauen</AN>,<RN>Experten</RN>,True,53.0,4.0,132.0,-223.0,-91.0,5.0,...,-631.0,-56.0,-3.0,1,0,-91.0,41.0,61.0,114.0,3
14,C2,<AN>Frauen</AN>,<RN>Einwohner</RN>,True,53.0,4.0,132.0,-179.0,-47.0,5.0,...,-608.0,-56.0,-3.0,1,0,-47.0,85.0,61.0,114.0,4
68,C3,<AN>Männer</AN>,<RN>Professorinnen</RN>,True,53.0,4.0,135.0,-65.0,70.0,5.0,...,778.0,-173.0,-120.0,1,0,70.0,205.0,61.0,114.0,13
65,C3,<AN>Männer</AN>,<RN>Dozentinnen</RN>,True,53.0,4.0,135.0,-339.0,-204.0,5.0,...,737.0,-173.0,-120.0,1,0,-204.0,-69.0,61.0,114.0,12
100,C3,<AN>Männer</AN>,<RN>Ingenieurinnen</RN>,True,53.0,4.0,135.0,-130.0,5.0,5.0,...,-494.0,-56.0,-3.0,1,0,5.0,140.0,61.0,114.0,18
33,C4,<AN>Frauen</AN>,<RN>Unternehmerinnen</RN>,True,53.0,4.0,132.0,-84.0,48.0,5.0,...,-446.0,-56.0,-3.0,1,0,48.0,180.0,61.0,114.0,7
98,C4,<AN>Frauen</AN>,<RN>Expertinnen</RN>,True,53.0,4.0,132.0,-63.0,69.0,5.0,...,-403.0,-56.0,-3.0,1,0,69.0,201.0,61.0,114.0,17
1,C4,<AN>Frauen</AN>,<RN>Krankenschwestern</RN>,True,53.0,4.0,132.0,-131.0,1.0,5.0,...,756.0,-173.0,-120.0,1,0,1.0,133.0,61.0,114.0,1
43,C5,<AN>Männer</AN>,<RN>Ingenieur*innen</RN>,True,53.0,4.0,135.0,115.0,250.0,5.0,...,-471.0,-56.0,-3.0,1,0,250.0,385.0,61.0,114.0,8
64,C5,<AN>Männer</AN>,<RN>Aktivist*innen</RN>,True,53.0,4.0,135.0,-201.0,-66.0,5.0,...,581.0,-173.0,-120.0,1,0,-66.0,69.0,61.0,114.0,11
21,C5,<AN>Männer</AN>,<RN>Arbeitnehmer*innen</RN>,True,53.0,4.0,135.0,-220.0,-85.0,5.0,...,-398.0,-56.0,-3.0,1,0,-85.0,50.0,61.0,114.0,5
24,C6,<AN>Frauen</AN>,<RN>Polizist*innen</RN>,True,53.0,4.0,132.0,-202.0,-70.0,5.0,...,304.0,-173.0,-120.0,1,0,-70.0,62.0,61.0,114.0,6
77,C6,<AN>Frauen</AN>,<RN>Lehrer*innen</RN>,True,53.0,4.0,132.0,-333.0,-201.0,5.0,...,231.0,-173.0,-120.0,1,0,-201.0,-69.0,61.0,114.0,14
97,C6,<AN>Frauen</AN>,<RN>Arbeitnehmer*innen</RN>,True,53.0,4.0,132.0,-105.0,27.0,6.0,...,-398.0,-56.0,-3.0,1,0,27.0,159.0,61.0,114.0,16