In [ ]:
import pandas as pd


csv_path = "subject-11.csv"

trial_data = pd.read_csv(csv_path)

In [54]:
trial_data_gezeigt = trial_data[trial_data["skip_trial"] == 0]
display(trial_data_gezeigt)

,AN,Code,RN,acc,accuracy,an_found,an_height,an_line,an_text,an_width,...,title,total_correct,total_response_time,total_responses,trial_counter,width,word,word_height,word_spacing,word_width
3,<AN>Männer</AN>,C3,<RN>Arbeitnehmerinnen</RN>,undefined,undefined,True,53.0,4.0,<AN>Männer</AN>,135.0,...,Experiment,0,0,0,1,1920,Diskussionen.,53.0,25.0,289.0
4,<AN>Männer</AN>,C5,<RN>Pfleger*innen</RN>,undefined,undefined,True,53.0,4.0,<AN>Männer</AN>,135.0,...,Experiment,0,0,0,2,1920,diskutiert.,53.0,25.0,243.0
6,<AN>Männern</AN>,C1,<RN>Experten</RN>,undefined,undefined,True,53.0,4.0,<AN>Männern</AN>,158.0,...,Experiment,0,0,0,3,1920,geprüft.,53.0,25.0,175.0
13,<AN>Frauen</AN>,C4,<RN>Einwohnerinnen</RN>,undefined,undefined,True,53.0,4.0,<AN>Frauen</AN>,132.0,...,Experiment,0,0,0,4,1920,Debatten.,53.0,25.0,197.0
21,<AN>Frauen</AN>,C6,<RN>Professor*innen</RN>,undefined,undefined,True,53.0,4.0,<AN>Frauen</AN>,132.0,...,Experiment,0,0,0,5,1920,diskutiert.,53.0,25.0,243.0
34,<AN>Männer</AN>,C5,<RN>Expert*innen</RN>,undefined,undefined,True,53.0,4.0,<AN>Männer</AN>,135.0,...,Experiment,0,0,0,6,1920,bewertet.,53.0,25.0,197.0
38,<AN>Männer</AN>,C1,<RN>Krankenpfleger</RN>,undefined,undefined,True,53.0,4.0,<AN>Männer</AN>,135.0,...,Experiment,0,0,0,7,1920,diskutiert.,53.0,25.0,243.0
48,<AN>Frauen</AN>,C6,<RN>Dozent*innen</RN>,undefined,undefined,True,53.0,4.0,<AN>Frauen</AN>,132.0,...,Experiment,0,0,0,8,1920,an.,53.0,25.0,59.0
55,<AN>Frauen</AN>,C6,<RN>Ingenieur*innen</RN>,undefined,undefined,True,53.0,4.0,<AN>Frauen</AN>,132.0,...,Experiment,0,0,0,9,1920,gestritten.,53.0,25.0,244.0
58,<AN>Frauen</AN>,C4,<RN>Studentinnen</RN>,undefined,undefined,True,53.0,4.0,<AN>Frauen</AN>,132.0,...,Experiment,0,0,0,10,1920,Debatten.,53.0,25.0,197.0
62,<AN>Männer</AN>,C3,<RN>Lehrerinnen</RN>,undefined,undefined,True,53.0,4.0,<AN>Männer</AN>,135.0,...,Experiment,0,0,0,11,1920,Diskussionen.,53.0,25.0,289.0
75,<AN>Männer</AN>,C3,<RN>Polizistinnen</RN>,undefined,undefined,True,53.0,4.0,<AN>Männer</AN>,135.0,...,Experiment,0,0,0,12,1920,verhandelt.,53.0,25.0,244.0
82,<AN>Frauen</AN>,C2,<RN>Aktivisten</RN>,undefined,undefined,True,53.0,4.0,<AN>Frauen</AN>,132.0,...,Experiment,0,0,0,13,1920,geprüft.,53.0,25.0,175.0
84,<AN>Frauen</AN>,C4,<RN>Expertinnen</RN>,undefined,undefined,True,53.0,4.0,<AN>Frauen</AN>,132.0,...,Experiment,0,0,0,14,1920,bewertet.,53.0,25.0,197.0
96,<AN>Frauen</AN>,C2,<RN>Arbeitnehmer</RN>,undefined,undefined,True,53.0,4.0,<AN>Frauen</AN>,132.0,...,Experiment,0,0,0,15,1920,offen.,53.0,25.0,129.0
99,<AN>Männer</AN>,C5,<RN>Einwohner*innen</RN>,undefined,undefined,True,53.0,4.0,<AN>Männer</AN>,135.0,...,Experiment,0,0,0,16,1920,Reaktionen.,53.0,25.0,242.0
100,<AN>Männer</AN>,C1,<RN>Unternehmer</RN>,undefined,undefined,True,53.0,4.0,<AN>Männer</AN>,135.0,...,Experiment,0,0,0,17,1920,umstritten.,53.0,25.0,243.0
106,<AN>Frauen</AN>,C2,<RN>Ingenieure</RN>,undefined,undefined,True,53.0,4.0,<AN>Frauen</AN>,132.0,...,Experiment,0,0,0,18,1920,diskutiert.,53.0,25.0,243.0

In [55]:
# Nur gezeigte Trials
trial_data_gezeigt = trial_data[trial_data["skip_trial"] == 0]

# Gewünschte Spalten
spalten = [
    "Code","AN", "RN",
    "an_found", "an_height", "an_line", "an_width",
    "an_x1", "an_x2",
    "current_line", "current_line_width",
    "datetime",
    "display_sentence",
    "experiment_file", "experiment_path",
    "item",
    "name",
    "rn_found", "rn_height", "rn_line", "rn_text",
    "rn_width", "rn_x1", "rn_x2", "rn_y1", "rn_y2",
    "selected_list",
    "skip_trial",
    "spill_x1", "spill_x2", "spill_y1", "spill_y2",
    "trial_counter"
]

# Tabelle erzeugen
trial_data_auswahl = trial_data_gezeigt[spalten]

display(trial_data_auswahl)

,Code,AN,RN,an_found,an_height,an_line,an_width,an_x1,an_x2,current_line,...,rn_x2,rn_y1,rn_y2,selected_list,skip_trial,spill_x1,spill_x2,spill_y1,spill_y2,trial_counter
3,C3,<AN>Männer</AN>,<RN>Arbeitnehmerinnen</RN>,True,53.0,4.0,135.0,-105.0,30.0,6.0,...,-421.0,-56.0,-3.0,4,0,30.0,165.0,61.0,114.0,1
4,C5,<AN>Männer</AN>,<RN>Pfleger*innen</RN>,True,53.0,4.0,135.0,-222.0,-87.0,6.0,...,-516.0,-56.0,-3.0,4,0,-87.0,48.0,61.0,114.0,2
6,C1,<AN>Männern</AN>,<RN>Experten</RN>,True,53.0,4.0,158.0,-63.0,95.0,5.0,...,-472.0,-56.0,-3.0,4,0,95.0,253.0,61.0,114.0,3
13,C4,<AN>Frauen</AN>,<RN>Einwohnerinnen</RN>,True,53.0,4.0,132.0,-309.0,-177.0,5.0,...,-493.0,-56.0,-3.0,4,0,-177.0,-45.0,61.0,114.0,4
21,C6,<AN>Frauen</AN>,<RN>Professor*innen</RN>,True,53.0,4.0,132.0,-65.0,67.0,5.0,...,801.0,-173.0,-120.0,4,0,67.0,199.0,61.0,114.0,5
34,C5,<AN>Männer</AN>,<RN>Expert*innen</RN>,True,53.0,4.0,135.0,-223.0,-88.0,5.0,...,-539.0,-56.0,-3.0,4,0,-88.0,47.0,61.0,114.0,6
38,C1,<AN>Männer</AN>,<RN>Krankenpfleger</RN>,True,53.0,4.0,135.0,-131.0,4.0,5.0,...,687.0,-173.0,-120.0,4,0,4.0,139.0,61.0,114.0,7
48,C6,<AN>Frauen</AN>,<RN>Dozent*innen</RN>,True,53.0,4.0,132.0,-339.0,-207.0,5.0,...,760.0,-173.0,-120.0,4,0,-207.0,-75.0,61.0,114.0,8
55,C6,<AN>Frauen</AN>,<RN>Ingenieur*innen</RN>,True,53.0,4.0,132.0,-130.0,2.0,5.0,...,-471.0,-56.0,-3.0,4,0,2.0,134.0,61.0,114.0,9
58,C4,<AN>Frauen</AN>,<RN>Studentinnen</RN>,True,53.0,4.0,132.0,-378.0,-246.0,5.0,...,396.0,-173.0,-120.0,4,0,-246.0,-114.0,61.0,114.0,10
62,C3,<AN>Männer</AN>,<RN>Lehrerinnen</RN>,True,53.0,4.0,135.0,-333.0,-198.0,5.0,...,414.0,-173.0,-120.0,4,0,-198.0,-63.0,61.0,114.0,11
75,C3,<AN>Männer</AN>,<RN>Polizistinnen</RN>,True,53.0,4.0,135.0,-202.0,-67.0,5.0,...,281.0,-173.0,-120.0,4,0,-67.0,68.0,61.0,114.0,12
82,C2,<AN>Frauen</AN>,<RN>Aktivisten</RN>,True,53.0,4.0,132.0,-201.0,-69.0,5.0,...,489.0,-173.0,-120.0,4,0,-69.0,63.0,61.0,114.0,13
84,C4,<AN>Frauen</AN>,<RN>Expertinnen</RN>,True,53.0,4.0,132.0,-309.0,-177.0,5.0,...,-562.0,-56.0,-3.0,4,0,-177.0,-45.0,61.0,114.0,14
96,C2,<AN>Frauen</AN>,<RN>Arbeitnehmer</RN>,True,53.0,4.0,132.0,-305.0,-173.0,5.0,...,-536.0,-56.0,-3.0,4,0,-173.0,-41.0,61.0,114.0,15
99,C5,<AN>Männer</AN>,<RN>Einwohner*innen</RN>,True,53.0,4.0,135.0,-179.0,-44.0,5.0,...,-470.0,-56.0,-3.0,4,0,-44.0,91.0,61.0,114.0,16
100,C1,<AN>Männer</AN>,<RN>Unternehmer</RN>,True,53.0,4.0,135.0,-197.0,-62.0,5.0,...,-561.0,-56.0,-3.0,4,0,-62.0,73.0,61.0,114.0,17
106,C2,<AN>Frauen</AN>,<RN>Ingenieure</RN>,True,53.0,4.0,132.0,-85.0,47.0,5.0,...,705.0,-173.0,-120.0,4,0,47.0,179.0,61.0,114.0,18

In [56]:
# Nur gezeigte Trials
trial_data_gezeigt = trial_data[trial_data["skip_trial"] == 0]

# Tabelle erzeugen
trial_data_auswahl = trial_data_gezeigt[spalten]

# Nach Code sortieren
trial_data_auswahl = trial_data_auswahl.sort_values(by="Code")

display(trial_data_auswahl)

,Code,AN,RN,an_found,an_height,an_line,an_width,an_x1,an_x2,current_line,...,rn_x2,rn_y1,rn_y2,selected_list,skip_trial,spill_x1,spill_x2,spill_y1,spill_y2,trial_counter
6,C1,<AN>Männern</AN>,<RN>Experten</RN>,True,53.0,4.0,158.0,-63.0,95.0,5.0,...,-472.0,-56.0,-3.0,4,0,95.0,253.0,61.0,114.0,3
38,C1,<AN>Männer</AN>,<RN>Krankenpfleger</RN>,True,53.0,4.0,135.0,-131.0,4.0,5.0,...,687.0,-173.0,-120.0,4,0,4.0,139.0,61.0,114.0,7
100,C1,<AN>Männer</AN>,<RN>Unternehmer</RN>,True,53.0,4.0,135.0,-197.0,-62.0,5.0,...,-561.0,-56.0,-3.0,4,0,-62.0,73.0,61.0,114.0,17
106,C2,<AN>Frauen</AN>,<RN>Ingenieure</RN>,True,53.0,4.0,132.0,-85.0,47.0,5.0,...,705.0,-173.0,-120.0,4,0,47.0,179.0,61.0,114.0,18
96,C2,<AN>Frauen</AN>,<RN>Arbeitnehmer</RN>,True,53.0,4.0,132.0,-305.0,-173.0,5.0,...,-536.0,-56.0,-3.0,4,0,-173.0,-41.0,61.0,114.0,15
82,C2,<AN>Frauen</AN>,<RN>Aktivisten</RN>,True,53.0,4.0,132.0,-201.0,-69.0,5.0,...,489.0,-173.0,-120.0,4,0,-69.0,63.0,61.0,114.0,13
75,C3,<AN>Männer</AN>,<RN>Polizistinnen</RN>,True,53.0,4.0,135.0,-202.0,-67.0,5.0,...,281.0,-173.0,-120.0,4,0,-67.0,68.0,61.0,114.0,12
62,C3,<AN>Männer</AN>,<RN>Lehrerinnen</RN>,True,53.0,4.0,135.0,-333.0,-198.0,5.0,...,414.0,-173.0,-120.0,4,0,-198.0,-63.0,61.0,114.0,11
3,C3,<AN>Männer</AN>,<RN>Arbeitnehmerinnen</RN>,True,53.0,4.0,135.0,-105.0,30.0,6.0,...,-421.0,-56.0,-3.0,4,0,30.0,165.0,61.0,114.0,1
58,C4,<AN>Frauen</AN>,<RN>Studentinnen</RN>,True,53.0,4.0,132.0,-378.0,-246.0,5.0,...,396.0,-173.0,-120.0,4,0,-246.0,-114.0,61.0,114.0,10
13,C4,<AN>Frauen</AN>,<RN>Einwohnerinnen</RN>,True,53.0,4.0,132.0,-309.0,-177.0,5.0,...,-493.0,-56.0,-3.0,4,0,-177.0,-45.0,61.0,114.0,4
84,C4,<AN>Frauen</AN>,<RN>Expertinnen</RN>,True,53.0,4.0,132.0,-309.0,-177.0,5.0,...,-562.0,-56.0,-3.0,4,0,-177.0,-45.0,61.0,114.0,14
34,C5,<AN>Männer</AN>,<RN>Expert*innen</RN>,True,53.0,4.0,135.0,-223.0,-88.0,5.0,...,-539.0,-56.0,-3.0,4,0,-88.0,47.0,61.0,114.0,6
4,C5,<AN>Männer</AN>,<RN>Pfleger*innen</RN>,True,53.0,4.0,135.0,-222.0,-87.0,6.0,...,-516.0,-56.0,-3.0,4,0,-87.0,48.0,61.0,114.0,2
99,C5,<AN>Männer</AN>,<RN>Einwohner*innen</RN>,True,53.0,4.0,135.0,-179.0,-44.0,5.0,...,-470.0,-56.0,-3.0,4,0,-44.0,91.0,61.0,114.0,16
21,C6,<AN>Frauen</AN>,<RN>Professor*innen</RN>,True,53.0,4.0,132.0,-65.0,67.0,5.0,...,801.0,-173.0,-120.0,4,0,67.0,199.0,61.0,114.0,5
48,C6,<AN>Frauen</AN>,<RN>Dozent*innen</RN>,True,53.0,4.0,132.0,-339.0,-207.0,5.0,...,760.0,-173.0,-120.0,4,0,-207.0,-75.0,61.0,114.0,8
55,C6,<AN>Frauen</AN>,<RN>Ingenieur*innen</RN>,True,53.0,4.0,132.0,-130.0,2.0,5.0,...,-471.0,-56.0,-3.0,4,0,2.0,134.0,61.0,114.0,9